version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: animal_shelter_db
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped